export type Property = { id:string; title:string; location:string; city:string; state:string; type:string; area:string; price:string; priceNum:number; image:string; verified:boolean; featured?:boolean; road:string; description:string };
export const properties: Property[] = [
{id:'p1',title:'Prime Agricultural Land',location:'Ballia, Uttar Pradesh',city:'Ballia',state:'Uttar Pradesh',type:'Agricultural Land',area:'5 Bigha',price:'₹38 Lakh',priceNum:3800000,image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',verified:true,featured:true,road:'30 ft road',description:'Open agricultural land with road access and nearby village connectivity.'},
{id:'p2',title:'Residential Plot Near Highway',location:'Lucknow, Uttar Pradesh',city:'Lucknow',state:'Uttar Pradesh',type:'Residential Plot',area:'2,400 sq.ft',price:'₹42 Lakh',priceNum:4200000,image:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80',verified:true,featured:true,road:'40 ft road',description:'Residential plot in a developing locality with easy highway connectivity.'},
{id:'p3',title:'Farm Land Investment Opportunity',location:'Golaghat, Assam',city:'Golaghat',state:'Assam',type:'Farm Land',area:'8 Bigha',price:'₹54 Lakh',priceNum:5400000,image:'https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=1200&q=80',verified:false,featured:true,road:'24 ft road',description:'Peaceful farm land suitable for agriculture, farmhouse or long-term investment.'},
{id:'p4',title:'Commercial Corner Plot',location:'Ghaziabad, Uttar Pradesh',city:'Ghaziabad',state:'Uttar Pradesh',type:'Commercial Plot',area:'1,800 sq.ft',price:'₹1.05 Cr',priceNum:10500000,image:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',verified:true,road:'60 ft road',description:'Corner commercial plot with strong visibility and city connectivity.'},
{id:'p5',title:'Affordable Village Land',location:'Ballia, Uttar Pradesh',city:'Ballia',state:'Uttar Pradesh',type:'Agricultural Land',area:'3 Bigha',price:'₹21 Lakh',priceNum:2100000,image:'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=1200&q=80',verified:false,road:'20 ft road',description:'Budget-friendly agricultural parcel with direct road access.'},
{id:'p6',title:'Industrial Land Near Corridor',location:'Ghaziabad, Uttar Pradesh',city:'Ghaziabad',state:'Uttar Pradesh',type:'Industrial Land',area:'1.2 Acre',price:'₹2.4 Cr',priceNum:24000000,image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',verified:true,road:'80 ft road',description:'Industrial-use opportunity close to major road and logistics routes.'}
];
export const states=['Uttar Pradesh','Assam','Bihar','Delhi','West Bengal','Maharashtra'];
